config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :mandalas
  resources :cells
  devise_for :users, controllers:{
      sessions: 'users/sessions'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cell.rb
class Cell < ApplicationRecord
  belongs_to :mandala
  default_scope -> { order(created_at: :asc) }
end

app/models/mandala.rb
class Mandala < ApplicationRecord
  belongs_to :user
  has_many :cells, dependent: :destroy
  accepts_nested_attributes_for :cells, allow_destroy: true
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :mandalas, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cells_controller.rb
class CellsController < ApplicationController
  # def index
  #   @cells = Cell.all
  # end

  # def show
  #   @cell = Cell.find(params[:id])
  # end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
end

app/controllers/mandalas_controller.rb
class MandalasController < ApplicationController
  def index
    @mandalas = current_user.mandalas.all
  end
  def show
    @mandala = current_user.mandalas.find(params[:id])
  end
  def new
    @mandala = Mandala.new
    9.times do |i|
      9.times do |j|
        @mandala.cells.build(row: i + 1, column: j + 1)
      end
    end
  end
  def create
    @mandala = current_user.mandalas.build(mandala_params)
    if @mandala.save
      redirect_to @mandala, :notice => "Successfully created mandala."
    else
      render :action => 'new'
    end
  end
  
  def edit
    @mandala = Mandala.find(params[:id])
  end
  def update
    @mandala = current_user.mandalas.find(params[:id])
    if @mandala.update(mandala_params)
      redirect_to @mandala, :notice  => "Successfully updated mandala."
    else
      render :action => 'edit'
    end
  end
  def destroy
    @mandala = Mandala.find(params[:id])
    @mandala.destroy
    redirect_to mandalas_url, :notice => "Successfully destroyed mandala."
  end

  private

  def mandala_params
    params.require(:mandala).permit(:name, cells_attributes: [:id, :body, :row, :column])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user
      @user = User.find(current_user.id)
    else
      render "/home/index"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cells_helper.rb
module CellsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mandaras_helper.rb
module MandarasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cells/index.html.erb
<h1>Cells</h1>

<ul>
  <% @cells.each do |cell| %>
    <li><%= cell.body %></li>
  <% end %>
</ul>

app/views/cells/show.html.erb
<h1>Cell Details</h1>

<p><strong>Body:</strong> <%= @cell.body %></p>
<p><strong>Row:</strong> <%= @cell.row %></p>
<p><strong>Column:</strong> <%= @cell.column %></p>

app/views/home/index.html.erb
<% content_for :scss do %>
  <%= stylesheet_link_tag 'home' %>
<% end %>
<% if !user_signed_in? %>
  <div class="des rounded-5 no-p relative fadeUp">
    <h1 class="mb-5 normal" style="text-align:left;">「アイデア出しをもっと手軽に」</h1>
    <%= image_tag 'product_des_1.png', size:18*18, alt: 'product-des', class: "absolute" %>
    <p>Idea Memory(Imemo)とは、</p>
    <p class="mb-5 normal">無料でマンダラートを作成できるサービスです。</p>
    <p class="normal">マンダラートを使い、スムーズにアイデア出しや目標決めを行いましょう</p>
  </div>
  <div class="des-2 rounded-5 no-p fadeUp">
    <ul class="mb-3 normal progrem">
        <li class="mb-3">マンダラートを印刷して書くのは、正直面倒</li>
        <li class="mb-3">中央のマスに書いたことを、外側のマスに書かないといけない</li>
        <li class="mb-3">すべてのマスを埋められない</li>
        <li class="mb-3">ほかの人のマンダラートを参考にして、書きたい</li>
    </ul>
    <p class="my-5 normal">そんな悩みを解決するサービスです。</p>
    <p class="mb-5 normal">アイデア出しや自己分析、目標決めをするときに、ご活用ください</p>
  </div>
  <h2 class="no-p">マンダラート作成機能</h2>
  <div class="visible no-p">
    スマホを横にしてください
  </div>
  <div class="title hidden">
    <input type="text" placeholder="タイトルを入力してください">
  </div>
  <div class="container-fluid center-block mb-4 hidden" style="max-width: 1000px; mx-height: 1000px;">
    <div class="row">
      <% range = 1..9 %>
      <% range.each do |i| %>
        <div class="col-sm-4 col-xs-4 p-1 fadeUp">
          <div class="container-fluid">
            <div class="row">
              <% range.each do |j| %>
                <div class="col-4 p-0">
                  <textarea class="cell" id="body<%= i %><%= j %>" cols="5" rows="2" wrap="soft" style=""></textarea>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
    <button id="pdf_print" class="btn btn-success print no-p mb-5 hidden">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
      </svg>
      pdfで保存
    </button>
  </div>
<% else %>
  <p class="mt-5">マンダラートを使ってアイデア出しを始めてみましょう</p>
  <p class="mb-5">今日もアイデアが溢れる1日をお過ごしください</p>
  <h2 class="m-5">マンダラート機能</h2>
  <%= link_to mandalas_path do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-grid-3x3-gap-fill" viewBox="0 0 16 16">
      <path d="M1 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2zM1 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V7zM1 12a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-2zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-2z"/>
    </svg>
  <% end %>
<% end %>

<script>
  for (let i = 1; i < 10; i++) {
    document.addEventListener("DOMContentLoaded", function () {
      var inTextarea1 = document.getElementById(`body5${i}`);
      var outTextarea1 = document.getElementById(`body${i}5`);
      
      var inTextarea2 = document.getElementById(`body${i}5`);
      var outTextarea2 = document.getElementById(`body5${i}`);
      
      inTextarea1.addEventListener("input", function () {
          outTextarea1.value = inTextarea1.value;
      });

      inTextarea2.addEventListener("input", function () {
          outTextarea2.value = inTextarea2.value;
      });
    });
  }
</script>

<script>
  var printButton = document.getElementById("pdf_print");
  printButton.addEventListener("click", function() {
    window.print();
  });
</script>

app/views/layouts/_header.html.erb
<header class="navbar fixed-top navbar-inverse" style="position: sticky;">
  <div class="container">
    <%= image_tag 'Imemo_Icon.png', size:9*9, alt: 'Icon' %>
      <ul class="nav navbar-nav navbar-right no-p">
        <% if !user_signed_in? %>
          <li>
            <%= link_to new_user_registration_path do %>
              <i class="fa-solid fa-user-plus"></i>  新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa-solid fa-right-to-bracket"></i>  ログイン
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa-solid fa-user"></i>  Home
            <% end %>
          </li>
          <li>
            <%= button_to destroy_user_session_path, method: :delete do %>
              <i class="fa-solid fa-right-from-bracket"></i>  ログアウト
            <% end %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Imemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :scss %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="no-p">
      <% if flash[:notice] %>
        <div class="alert alert-info no-p">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

<!-- 
                                    !!!!!!!!!!!!
                                  !!            !!
                                !!                !!
                                !!      !!!       !!
                                !!      !!!       !!
                                  !!    !!!     !!
                                    !!   I    !!
                                     !!      !!
                                      !!!!!!!!
                                      !!!!!!!!
                                        !!!!
                       
      !!!!!!!!!!!
          !!!
          !!!
          !!!
          !!!     !!!!!!!!!!!!!!!!     !!!!!!!     !!!!!!!!!!!!!!!!!       !!!!!!
          !!!       !!!    !!   !!   !!!     !!!     !!!    !!    !!     !!!    !!!
          !!!       !!!    !!   !!  !!!!!!!!!!!!     !!!    !!    !!    !!!      !!!
          !!!       !!!    !!   !!  !!!              !!!    !!    !!     !!!    !!!
     !!!!!!!!!!!!!  !!!    !!   !!   !!!!!!!!!!      !!!    !!    !!       !!!!!!

-->

app/views/mandalas/edit.html.erb
<% content_for :scss do %>
  <%= stylesheet_link_tag 'home' %>
<% end %>
<%= form_with model: @mandala do |form| %>
  <div class="field m-3">
    <%= form.text_field :name, placeholder: "タイトル" %>
  </div>
  <div class="container-fluid center-block" style="max-width: 1000px;">
    <div class="row">
      <%= form.fields_for :cells do |cell_form| %>
        <% if cell_form.object&.column == 1 %>
        <div class="col-sm-4 p-1">
          <div class="container-fluid">
            <div class="row">
        <% end %>
        <div class="col-4 p-0">
          <%= cell_form.text_area :body, id: "body#{cell_form.object&.row}#{cell_form.object&.column}", class: "cell"%>
          <%= cell_form.hidden_field :row, value: cell_form.object&.row %>
          <%= cell_form.hidden_field :column, value: cell_form.object&.column %>
        </div>
        <% if cell_form.object&.column == 9 %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  for (let i = 1; i < 10; i++) {
    document.addEventListener("DOMContentLoaded", function () {
      var inTextarea1 = document.getElementById(`body5${i}`);
      var outTextarea1 = document.getElementById(`body${i}5`);
      
      var inTextarea2 = document.getElementById(`body${i}5`);
      var outTextarea2 = document.getElementById(`body5${i}`);
      
      inTextarea1.addEventListener("input", function () {
          outTextarea1.value = inTextarea1.value;
      });

      inTextarea2.addEventListener("input", function () {
          outTextarea2.value = inTextarea2.value;
      });
    });
  }
</script>

app/views/mandalas/index.html.erb
<h1 class="m-5">マンダラートの一覧</h1>
  <% if @mandalas %>
    <% @mandalas.each do |mandala| %>
      <div class="m-5">
        <%= mandala.name %><br>
        <%= link_to '詳細を見る', mandala_path(mandala) %>
      </div>
    <% end %>
  <% end %>
<div class="m-5">
  <%= link_to '新規作成', new_mandala_path %>
</div>

app/views/mandalas/new.html.erb
<% content_for :scss do %>
  <%= stylesheet_link_tag 'home' %>
<% end %>
<%= form_with model: @mandala do |form| %>
  <div class="field m-5">
    <%= form.text_field :name, placeholder: "title" %>
  </div>
  <div class="container-fluid center-block" style="max-width: 1000px;">
    <div class="row">
      <%= form.fields_for :cells do |cell_form| %>
        <% if cell_form.object&.column == 1 %>
        <div class="col-sm-4 p-1">
          <div class="container-fluid">
            <div class="row">
        <% end %>
        <div class="col-4 p-0">
          <%= cell_form.text_area :body, id: "body#{cell_form.object&.row}#{cell_form.object&.column}", class: "cell" %>
          <%= cell_form.hidden_field :row, value: cell_form.object&.row %>
          <%= cell_form.hidden_field :column, value: cell_form.object&.column %>
        </div>
        <% if cell_form.object&.column == 9 %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
      </div>
      </div>
    </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<script>
  for (let i = 1; i < 10; i++) {
    document.addEventListener("DOMContentLoaded", function () {
      var inTextarea1 = document.getElementById(`body5${i}`);
      var outTextarea1 = document.getElementById(`body${i}5`);
      
      var inTextarea2 = document.getElementById(`body${i}5`);
      var outTextarea2 = document.getElementById(`body5${i}`);
      
      inTextarea1.addEventListener("input", function () {
          outTextarea1.value = inTextarea1.value;
      });

      inTextarea2.addEventListener("input", function () {
          outTextarea2.value = inTextarea2.value;
      });
    });
  }
</script>

app/views/mandalas/show.html.erb
<% content_for :scss do %>
  <%= stylesheet_link_tag 'home' %>
<% end %>
<div class="title">
  <%= @mandala.name %>
</div>
<div class="container-fluid center-block" style="max-width: 1000px;">
  <div class="row">
    <% @mandala.cells.each do |cell| %>
      <% if cell.column == 1 %>
      <div class="col-sm-4 p-1">
        <div class="container-fluid">
          <div class="row">
      <% end %>
      <div class="col-4 p-0">
        <textarea class="cell" id="body<%= cell.row %><%= cell.column %>" cols="5" rows="2" wrap="soft" style="" readonly><%= cell.body%></textarea>
      </div>
      <% if cell.column == 9 %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<div class="no-p">
  <%= link_to '一覧を見る', mandalas_path %>
  <%= link_to '新規作成', new_mandala_path %>
  <%= link_to '編集する', edit_mandala_path(@mandala) %>
  <button id="pdf_print" class="btn btn-success print">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
        <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
        <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
      </svg>
      pdfで保存
  </button>
  <%= button_to '削除する', mandala_path(@mandala), method: :delete %>
</div>
<script>
  var printButton = document.getElementById("pdf_print");
  printButton.addEventListener("click", function() {
    window.print();
  });
</script>

app/views/users/show.html.erb
<h1><%= @user.name %>の詳細ページ</h1>
<%= @user.name %>
<%= @user.email %>
<% if @user.mandalas.any? %>
  <h3><%= @user.mandalas.count %>個のマンダラートを作成しています</h3>
  <ul >
    <% @user.mandalas.each do |mandala| %>
      <li><%= mandala.name %></li>
    <% end %>
  </ul>
<% end %>